server: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ccfish.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      # 单机 defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com #注册进eureka的名字
    prefer-ip-address: true #显示ip提示
info:
  app.name: ccfish-microservicecloud
  company.name: www.qqhapi.com
  build.artifactId: $project.artifactId$ #pom中build配置，读取pom内容
  build.version: $project.version$
---
server: 
  port: 8001
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ccfish.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      # 单机 defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com #注册进eureka的名字
    prefer-ip-address: true #显示ip提示
info:
  app.name: ccfish-microservicecloud
  company.name: www.qqhapi.com
  build.artifactId: $project.artifactId$ #pom中build配置，读取pom内容
  build.version: $project.version$